// ============================================================================
//  harvest.m  --  automorphism-quotient harvest for completely decomposable
//                 modular Jacobians (Ekedahl-Serre gap filling)
//
//  Depends on the GL2 package shipped with
//    github.com/AndrewVSutherland/CompletelyDecomposableModularJacobians
//  (which bundles AndrewVSutherland/Magma as a submodule and gl2split.m).
//
//  Run:   magma -b
//         > AttachSpec("spec");
//         > load "harvest.m";
//
//  KEY FACT (Poincare reducibility): if J_H is isogenous to a product of
//  elliptic curves, then so is every isogeny factor, hence J(X_H / B) is
//  completely decomposable for EVERY B <= Aut(X_H).  So every quotient curve
//  we produce automatically has a completely decomposable Jacobian; the only
//  question is which genera arise.  Validated on LMFDB data: the five modular
//  quotients of 60.480.37.bg.1 (genera 3,9,15,17,19) are all completely
//  decomposable.
//
//  The modular automorphisms of X_H are exactly N(H)/H, where N(H) is the
//  normalizer of H in GL2(Zhat) (Atkin-Lehner + diamond + Fricke live here).
//  A quotient of X_H by a subgroup of N(H)/H is the modular curve X_B for the
//  intermediate group H <= B <= N(H); its genus is GL2Genus(B).  So the
//  quotient-genus harvest reduces to: enumerate B between H and N(H) (keeping
//  det(B) = Zhat^x and -I in B so X_B is nice over Q) and record GL2Genus(B).
// ============================================================================

// KnownRealizedGenera(): the consolidated Paulhus-Sutherland set.
// Must be defined before GAPS references it.
function KnownRealizedGenera()
    R := [<0,37>,<38,38>,<39,55>,<57,58>,<61,65>,<67,69>,<71,73>,<75,78>,
          <79,82>,<85,85>,<89,89>,<91,91>,<93,93>,<95,95>,<97,97>,<101,101>,
          <103,103>,<105,107>,<109,109>,<113,113>,<118,118>,<121,121>,
          <125,125>,<129,129>,<135,135>,<137,137>,<142,142>,<145,145>,
          <154,154>,<157,157>,<159,159>,<161,161>,<163,163>,<169,169>,
          <193,193>,<199,199>,<205,205>,<211,211>,<213,213>,<217,217>,
          <244,244>,<257,257>,<325,325>,<409,409>,<433,433>,<649,649>,
          <1297,1297>];
    known := {Integers()|};
    for t in R do
        for g in [t[1]..t[2]] do Include(~known, g); end for;
    end for;
    return known;
end function;

// ---- targets: genera not yet realized (from the LMFDB-derived gap list) ----
GAPS := {Integers()| g : g in [56..1297]} diff KnownRealizedGenera();

// ---------------------------------------------------------------------------
// Part A.  Quotient harvest over the completely decomposable census.
//   Input  : grpdata.txt rows (label N.i.g.c.n) with J_H completely decomposable.
//   Output : every quotient genus GL2Genus(B) for H <= B <= N(H), flagged if
//            it lands in GAPS.  Focus on the >100,000 sources of genus > 100.
// ---------------------------------------------------------------------------

function ModularQuotientGenera(H)
    // H : subgroup of GL(2,Z/NZ) of level N, det index 1, -I in H.
    N := GL2Level(H);
    G := GL2Ambient(N);
    Nz := Normalizer(G, H);                 // N(H) in GL2(Z/NZ)
    // intermediate groups H <= B <= Nz, up to conjugacy in Nz
    L := [ B`subgroup : B in Subgroups(Nz : OrderMultipleOf := #H) |
                        #B`subgroup mod #H eq 0 and H subset B`subgroup ];
    gen := {Integers()|};
    for B in L do
        if GL2DeterminantIndex(B) eq 1 and (-G!1) in B then
            Include(~gen, GL2Genus(B));     // genus of the quotient curve X_B
        end if;
    end for;
    return gen;
end function;

procedure HarvestCensus(infile, outfile : MinGenus := 100)
    fp := Open(outfile, "w");
    new := {Integers()|};
    for line in Split(Read(infile), "\n") do
        if #line eq 0 or line[1..1] eq "#" then continue; end if;
        r := Split(line, ":");
        if #r lt 4 then continue; end if;
        H := GL2FromGenerators(r[1], r[2], r[4]);  // level, index, generators
        if GL2Genus(H) lt MinGenus then continue; end if;
        for g in ModularQuotientGenera(H) do
            if g in GAPS and not (g in new) then
                Include(~new, g);
                fprintf fp, "%o\t%o\t(source %o)\n", g, "NEW", line;
            end if;
        end for;
    end for;
    delete fp;
    printf "Census harvest: %o new genera filled: %o\n", #new, Sort(SetToSequence(new));
end procedure;

// ---------------------------------------------------------------------------
// Part B.  Atkin-Lehner harvest over the X_0(N) family (N <= 1200 with
//   J_0(N) completely decomposable).
//
//   The Atkin-Lehner group of X_0(N) is generated by {w_{p^v_p(N)} : p | N}.
//   Its non-trivial elements are the exact divisors d > 1 of N (i.e. d | N and
//   gcd(d, N/d) = 1); for composite N there are 2^k - 1 of them (k = #primes).
//   The quotient curve X_0(N)/⟨w_d⟩ is a SINGLE involution quotient; its genus
//   equals dim ker(M_d - I) where M_d = ∏_{p | d} AL_{p^v_p(N)} acting on
//   S_2(Gamma_0(N)).  This is different from intersecting eigenspaces: w_24 on
//   X_0(600) is a single involution w_8·w_3, so M_{24} = AL_8·AL_3 and
//   genus = dim ker(M_{24} - I) = 47.
//
//   Note: GL2Borel + Normalizer cannot capture Atkin-Lehner involutions for
//   composite N (the AL matrices have non-unit diagonal entries mod N), so we
//   use Magma's built-in modular symbols instead.
//
//   GOOD_N (86 levels, computed from LMFDB classical-newform data; the X_0(N)
//   genera reproduce Yamauchi's published list exactly):
// ---------------------------------------------------------------------------

GOOD_N := [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,24,25,26,27,
  28,30,32,33,34,36,37,38,40,42,44,45,48,49,50,52,54,56,57,60,64,66,72,75,76,80,
  84,90,96,99,100,108,112,114,120,121,128,132,144,150,168,180,192,198,200,216,
  240,288,300,336,360,384,396,400,432,576,600,720,1152,1200];

// Genus of X_0(N)/⟨w_d⟩: dim of +1 eigenspace of the product matrix M_d.
// al_pp_mats[i] = Matrix(AtkinLehner(S, ppeds[i])), ppeds = [p^v_p(N) : p | N].
function X0QuotientGenus(gN, al_pp_mats, ppeds, d)
    n := gN;
    I_n := IdentityMatrix(Rationals(), n);
    M_d := I_n;
    for i := 1 to #ppeds do
        if d mod ppeds[i] eq 0 then M_d := M_d * al_pp_mats[i]; end if;
    end for;
    return n - Rank(M_d - I_n);
end function;

procedure HarvestX0AtkinLehner(outfile)
    fp := Open(outfile, "w");
    new := {Integers()|};
    for N in GOOD_N do
        // All exact divisors d > 1 of N: one per non-trivial AL group element.
        exact_divs := [d : d in Divisors(N) | d gt 1 and GCD(d, N div d) eq 1];
        if #exact_divs eq 0 then continue; end if;
        // Prime-power parts of N: generators of the AL group.
        ppeds := [p^Valuation(N, p) : p in PrimeDivisors(N)];
        // Modular symbols space for X_0(N).
        MS := ModularSymbols(N, 2, +1);
        S := CuspidalSubspace(MS);
        gN := Dimension(S);
        if gN eq 0 then continue; end if;
        // Precompute AL matrices for prime-power generators.
        al_pp_mats := [Matrix(AtkinLehner(S, pp)) : pp in ppeds];
        // For each exact divisor d > 1, compute genus of X_0(N)/⟨w_d⟩.
        for d in exact_divs do
            g := X0QuotientGenus(gN, al_pp_mats, ppeds, d);
            if g in GAPS and not (g in new) then
                Include(~new, g);
                fprintf fp, "%o\tNEW\tX_0(%o)/w_%o Atkin-Lehner quotient\n", g, N, d;
            end if;
        end for;
    end for;
    delete fp;
    printf "X_0(N) AL harvest: %o new genera: %o\n", #new, Sort(SetToSequence(new));
end procedure;

// ---------------------------------------------------------------------------
// Sanity anchor: X_0(600)/w_24 must come out as genus 47 (Ekedahl-Serre).
// 600 = 8 * 3 * 25; d=24 has prime factors 2 and 3, so M_24 = AL_8 * AL_3.
// ---------------------------------------------------------------------------
procedure CheckAnchor()
    N := 600;
    ppeds := [p^Valuation(N, p) : p in PrimeDivisors(N)];  // [8, 3, 25]
    MS := ModularSymbols(N, 2, +1);
    S := CuspidalSubspace(MS);
    gN := Dimension(S);
    al_pp_mats := [Matrix(AtkinLehner(S, pp)) : pp in ppeds];
    g := X0QuotientGenus(gN, al_pp_mats, ppeds, 24);
    assert g eq 47;
    printf "Anchor OK: g(X_0(600)/w_24) = %o.\n", g;
end procedure;

// Entry point:
//   CheckAnchor();
//   HarvestX0AtkinLehner("x0_al_newgenera.txt");
//   HarvestCensus("grpdata.txt", "census_newgenera.txt" : MinGenus := 100);
